Updating application.html to more closely resemble a real application
agpalm25/Epic_Exec_CS321_CORE_APP pull request #9
Opened 2024-10-30 15:42 UTC by agpalm25

After looking at the application, I just pushed out our html copy of what this will look like. I'll work on the .css styling for this and script to make it work properly later.

2024-10-31 03:23 UTC, akiola submitted a review, later dismissed
Some fields do not have text boxes 

- PREFERRED Name:
- Colby College Email Address:
- Academic Major (2)

2024-10-31 03:47 UTC, James23xr requested changes
Webpage looks great! The codebase does not break either which is great! If application.html can be integrated into home.html it'll be easier to access than manually entering the url extension. I second to Godfred's suggestions as well. Aside that, it looks great!

2024-11-03 21:34 UTC, James23xr approved these changes
Extra information provided for application page.Website still functions as expected with added functionality

2024-11-03 21:35 UTC, Christian-Kofi-Okyere approved these changes

2024-11-03 21:36 UTC, merged